package shared.model.entities;

import jakarta.persistence.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


// Find the Spring Boot database documentation here: (https://docs.spring.io/spring-boot/reference/data/sql.html)
// Good guide on JPA here: https://www.infoworld.com/article/2259742/java-persistence-with-jpa-and-hibernate-part-1-entities-and-relationships.html
// Find a good manual on how to use Spring Boot with JPA Database management here: https://medium.com/@bubu.tripathy/best-practices-entity-class-design-with-jpa-and-spring-boot-6f703339ab3d
@Entity // Assigns this class as an Entity for Spring Boot, to use as a base for its Data Persistance interface.
@Table(name="Animal") // Tells spring boot JPA, what the name of this database table is.
public class Animal implements Serializable
{
  @Id                                                   // Tells Spring Boot, that this value is the primary key.
  @GeneratedValue (strategy = GenerationType.SEQUENCE, generator = "animal_id_seq_generator")  // Tells Spring Boot, that the primary key is generated by the database, using a sequence, and defines the specific generator in the database to utilize.
  @SequenceGenerator(name = "animal_id_seq_generator", sequenceName = "animal_animal_id_seq", allocationSize = 1) // Read documentation here: https://javabeat.net/jpa-annotations-generatedvalue-sequencegenerator-tablegenerator/
  private long animalId;


  @Column (nullable=false) // Tells Spring Boot, that this is a column in the database, and that it cannot be null.
  private BigDecimal weight_kilogram;


  // @OneToMany Tells Spring Boot, that this database entity has a OneToMany relationship with the AnimalPart entity,
  // and that the AnimalPart entity should 'own' the mapping. In other words, the animal assigned in the 'AnimalPart' entity should be prioritized.
  // This makes logical sense, since it is from within the AnimalPart class that references to the Animal are stored in the DB!
  @OneToMany(mappedBy="animal", orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
  private List<AnimalPart> partList;


  @Transient
  private List<Long> animalPartIdList = new ArrayList<>();


  // A no-args constructor, as required by the Java Data API (JPA) specifications.
  public Animal() {
    //JPA requires this to be blank!
  }


  public Animal(BigDecimal weight_kilogram) {
    setWeight_kilogram(weight_kilogram);
    partList = new ArrayList<>();
  }


  public Animal(long id, BigDecimal weight_kilogram) {
    setWeight_kilogram(weight_kilogram);
    setId(id);
    partList = new ArrayList<>();
  }


  public BigDecimal getWeight_kilogram() {
    return weight_kilogram;
  }


  public void setWeight_kilogram(BigDecimal weight) {
    this.weight_kilogram = weight;
  }


  public long getId() {
    return animalId;
  }


  public void setId(long animal_id) {
    this.animalId = animal_id;
  }


  public List<AnimalPart> getPartList() {
    return partList;
  }


  public void setAnimalParts(List<AnimalPart> animalParts) {
    this.partList = animalParts;
    // Ensure that all assigned AnimalParts have this Animal as the parent:
    for (AnimalPart animalPart : animalParts) {
      animalPart.setAnimal(this);
    }
  }


  public void addAnimalPart(AnimalPart animalPart) {
    // Set parent Animal to this Animal when adding:
    animalPart.setAnimal(this);
    this.partList.add(animalPart);
  }


  public void removeAnimalPart(AnimalPart animalPart) {
    // Set parent Animal to NULL when removing.
    this.partList.remove(animalPart);
    animalPart.setAnimal(null);
  }


  public List<Long> getAnimalPartIdList() {
    return animalPartIdList;
  }

  public void setAnimalPartIdList(List<Long> animalPartIds) {
    this.animalPartIdList = animalPartIds;
  }


  // TODO: Update/Review equals, toString and hashcode methods
  // Required by Spring Boot JPA:
  @Override public boolean equals(Object o) {
    if (o == null || this.getClass() != o.getClass())
      return false;

    return Objects.equals(getWeight_kilogram(), ((Animal) o).getWeight_kilogram())
        && Objects.equals(getId(), ((Animal) o).getId())
        && Objects.equals(getPartList(), ((Animal) o).getPartList()); //TODO Confirm that this equals method also performs equals check on contents.
  }


  // Required by Spring Boot JPA:
  @Override public int hashCode() {
    return Objects.hash(animalId, getWeight_kilogram(), getPartList());
  }


  @Override public String toString() {
    String returnValue = "animal_id: '"
        + getId()
        + "', weight: '"
        + getWeight_kilogram()
        +  "kg', animalPart_ids cut from this animal: [";

    for (int i = 0; i < getPartList().size(); i++) {
      returnValue += getPartList().get(i).getPart_id();
      if(i != getPartList().size() - 1)
        returnValue += ", ";
      else
        returnValue += "]";
    }
        
    return returnValue;
  }


  public Animal copy() {
    Animal animalCopy = new Animal(getWeight_kilogram());
    animalCopy.setId(getId());
    for (AnimalPart animalPart : getPartList()) {
      animalCopy.getPartList().add(animalPart);
    }
    return animalCopy;
  }
}
