package shared.model.entities;

import jakarta.persistence.*;
import org.springframework.dao.DataIntegrityViolationException;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Objects;

// Find the Spring Boot database documentation here: (https://docs.spring.io/spring-boot/reference/data/sql.html)
// Good guide on JPA here: https://www.infoworld.com/article/2259742/java-persistence-with-jpa-and-hibernate-part-1-entities-and-relationships.html
// Find a good manual on how to use Spring Boot with JPA Database management here: https://medium.com/@bubu.tripathy/best-practices-entity-class-design-with-jpa-and-spring-boot-6f703339ab3d
@Entity // Assigns this class as an Entity for Spring Boot, to use as a base for its Data Persistance interface.
@Table(name="tray") // Tells spring boot JPA, what the name of this database table is.
public class Tray implements Serializable
{
  @Id                                                   // Tells Spring Boot, that this value is the primary key.
  @GeneratedValue (strategy = GenerationType.SEQUENCE, generator = "tray_id_generator")  // Tells Spring Boot, that the primary key is generated by the database, using a sequence, and defines the specific generator in the database to utilize.
  @SequenceGenerator(name = "tray_id_generator", sequenceName = "tray_tray_id_seq", allocationSize = 1) // Read documentation here: https://javabeat.net/jpa-annotations-generatedvalue-sequencegenerator-tablegenerator/
  private long trayId;


  @Column(name="maxweight_kilogram", nullable=false) // Tells Spring Boot, that this is a column in the database, and that it cannot be null.
  private BigDecimal maxWeight_kilogram;


  @Column(name="weight_kilogram", nullable=false) // Tells Spring Boot, that this is a column in the database, and that it cannot be null.
  private BigDecimal weight_kilogram;


  // @OneToMany Tells Spring Boot, that this database entity has a OneToMany relationship with the AnimalPart entity,
  // and that the AnimalPart entity should 'own' the mapping. In other words, the tray_id assigned in the 'AnimalPart' entity should be prioritized.
  // This makes logical sense, since it is from within the AnimalPart class that references to the Tray are stored!
  @OneToMany(mappedBy= "tray", orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
  private List<AnimalPart> contents;


  // Special Note: JPA works with Database entities as objects, so the join table is here modelled as its own object. This allows for future scalability,
  // where I can decide to add timestamp, etc. to the join table without much change to this code!
  // @OneToMany Tells Spring Boot, that this database entity has a OneToMany relationship with the TrayToProductTransferRepository entity,
  // also that TrayToProductTransferRepository entity should 'own' the mapping (using the tray attribute in its class).
  // This makes logical sense, since it is from within the TrayToProductTransferRepository class that references to the Tray are stored in the DB, between Product and Tray.
  @OneToMany(mappedBy="tray", fetch = FetchType.EAGER)
  private List<TrayToProductTransfer> transferList = new ArrayList<>();

  @Transient
  private PartType trayType;

  @Transient
  private List<Long> animalPartIdList = new ArrayList<>();

  @Transient
  private List<Long> transferIdList = new ArrayList<>();

  @Transient
  private List<Product> productList = new ArrayList<>();

  // A no-args constructor, as required by the Java Data API (JPA) specifications. Should not be used directly, thus protected!
  protected Tray() {
    //JPA requires this to be blank!
  }


  public Tray(Long trayId, BigDecimal maxWeight_kilogram, BigDecimal weight_kilogram, List<Long> contentIdList, List<Long> transferIdList) {
    setTrayId(trayId);
    setMaxWeight_kilogram(maxWeight_kilogram);
    setWeight_kilogram(weight_kilogram);

    if(contentIdList != null && !contentIdList.isEmpty())
      this.animalPartIdList.addAll(contentIdList);

    if(transferIdList != null && !transferIdList.isEmpty())
      this.transferIdList.addAll(transferIdList);
  }


  public BigDecimal getMaxWeight_kilogram() {
    return maxWeight_kilogram;
  }


  public void setMaxWeight_kilogram(BigDecimal maxCapacity) {
    this.maxWeight_kilogram = maxCapacity;
  }


  public BigDecimal getWeight_kilogram() {
    return weight_kilogram;
  }


  public void setWeight_kilogram(BigDecimal currentWeight) {
    this.weight_kilogram = currentWeight;
  }


  public long getTrayId() {
    return trayId;
  }


  public void setTrayId(long tray_id) {
    this.trayId = tray_id;
  }


  /** Returns a copy of the contents. Any manipulation of the copy will NOT be saved to this object. */
  public List<AnimalPart> getContents() {
    if(contents == null)
      return new ArrayList<>();
    else
      return new ArrayList<>(contents);
  }


  public void addAnimalPart(AnimalPart animalPart) throws DataIntegrityViolationException {
    // Check that there is room for more animalParts:
    BigDecimal availableCapacity = getMaxWeight_kilogram().subtract(getWeight_kilogram());

    if(availableCapacity.subtract(animalPart.getWeight_kilogram()).compareTo(BigDecimal.valueOf(0)) < 0) {
      //There isn't space for this AnimalPart
      throw new DataIntegrityViolationException("Unable to add AnimalPart. Tray available Capacity (" + availableCapacity + "kg) is less than required (" + availableCapacity.subtract(animalPart.getWeight_kilogram()) + ")");
    }

    // Check that AnimalPart has the same PartType association, as this Tray:
    if (getTrayType() == null || getContents().isEmpty()) {
      // This is the first AnimalPart being added. This part defines what AnimalParts this Tray may transport:
      setTrayType(animalPart.getType());
    } else {
      if(animalPart.getType().getTypeId() != getTrayType().getTypeId()) {
        throw new DataIntegrityViolationException("Unable to add AnimalPart. Trays may only contain 1 AnimalPart type. Tray already contains '" + getTrayType().getTypeDesc() + "', but attempting to add '" + animalPart.getType().getTypeDesc() + "'");
      }
    }

    // Add the AnimalPart:
    if(contents != null) {
      animalPart.setTray(this);
      contents.add(animalPart);
      setWeight_kilogram(getWeight_kilogram().add(animalPart.getWeight_kilogram()));
    } else {
      contents = new ArrayList<>();
      animalPart.setTray(this);
      contents.add(animalPart);
      setWeight_kilogram(getWeight_kilogram().add(animalPart.getWeight_kilogram()));
    }
  }


  public void removeAnimalPart(AnimalPart animalPart) {
    if(contents != null) {
      animalPart.setTray(null);
      contents.remove(animalPart);
    }
  }


  public void clearAnimalPartContents() {
    if(contents != null)
      contents.clear();
  }


  public void addAllAnimalParts (Collection<AnimalPart> animalPartCollection) throws DataIntegrityViolationException {
    for (AnimalPart animalPart : animalPartCollection)
      addAnimalPart(animalPart);
  }


  public List<Long> getAnimalPartIdList() {
    return animalPartIdList;
  }


  public void setAnimalPartIdList(List<Long> animalPartIds) {
    this.animalPartIdList = animalPartIds;
  }


  public List<Long> getTransferIdList() {
    return transferIdList;
  }


  public void setTransferIdList(List<Long> transferIds) {
    this.transferIdList = transferIds;
  }

  public List<TrayToProductTransfer> getTransferList() {
    if(transferList == null)
      return new ArrayList<>();
    else
      return transferList;
  }


  public void setTransferList(List<TrayToProductTransfer> deliveredToProducts) {
    if(deliveredToProducts == null)
      this.transferList = new ArrayList<>();
    else
      this.transferList = deliveredToProducts;
  }

  public List<Product> getProductList() {
    return productList;
  }

  public void setProductList(List<Product> productList) {
    this.productList = productList;
  }


  public PartType getTrayType() {
    return trayType;
  }


  public void setTrayType(PartType trayType) {
    this.trayType = trayType;
  }


  // TODO: Update/Review equals, toString and hashcode methods
  @Override public boolean equals(Object o) {
    if (this == o)
      return true;
    if (o == null || getClass() != o.getClass())
      return false;
    Tray tray = (Tray) o;
    return getTrayId() == tray.getTrayId()
        && Objects.equals(getMaxWeight_kilogram(), tray.getMaxWeight_kilogram())
        && Objects.equals(getWeight_kilogram(), tray.getWeight_kilogram())
        && Objects.equals(getContents(), tray.getContents())
        && Objects.equals(getTransferList(), tray.getTransferList())
        && Objects.equals(getTrayType(), tray.getTrayType())
        && Objects.equals(getAnimalPartIdList(), tray.getAnimalPartIdList())
        && Objects.equals(getTransferIdList(), tray.getTransferIdList())
        && Objects.equals(getProductList(), tray.getProductList());
  }

  @Override public int hashCode() {
    return Objects.hash(getTrayId(),
        getMaxWeight_kilogram(),
        getWeight_kilogram(),
        getContents(),
        getTransferList(),
        getTrayType(),
        getAnimalPartIdList(),
        getTransferIdList(),
        getProductList());
  }

  @Override public String toString() {
    String returnValue = "tray_id: '"
        + getTrayId()
        + ", maxCapacity: '"
        + getMaxWeight_kilogram()
        + "kg, currentWeight: '"
        + getWeight_kilogram()
        + "kg', only holds partType: '";

    returnValue += (getTrayType() != null) ? getTrayType().getTypeDesc() : "NULL";
    returnValue += "', product_id's parts were handed to: [";

    for (int i = 0; i < getTransferList().size(); i++) {
      returnValue += getTransferList().get(i).getProduct().getProductId();
      if(i != getTransferList().size() - 1)
        returnValue += ", ";
    }
    returnValue += "], animalPart_id's in Tray: [";

    for (int i = 0; i < getContents().size(); i++) {
      returnValue += getContents().get(i).getPart_id();
      if(i != getContents().size() - 1)
        returnValue += ", ";
    }
    returnValue += "]";

    return returnValue;
  }


  public Tray copy() {
    Tray trayCopy = new Tray();
    trayCopy.setTrayId(getTrayId());
    trayCopy.setTrayType(getTrayType());
    trayCopy.setWeight_kilogram(getWeight_kilogram());
    trayCopy.setMaxWeight_kilogram(getMaxWeight_kilogram());
    trayCopy.addAllAnimalParts(getContents());
    trayCopy.getTransferList().addAll(getTransferList());

    return trayCopy;
  }
}
